from enum import Enum

API_ENDPOINT = "https://data.cms.gov/data-api/v1/dataset/6219697b-8f6c-4164-bed4-cd9317c58ebc/data"

class Geography(str, Enum):
    NATIONAL = "National"
    STATE = "State"
    COUNTY = "County"

class Measure(str, Enum):
    BENEFICIARIES_COUNT = "beneficiaries_count"
    BENEFICIARY_GENDER = "beneficiary_gender"
    BENEFICIARY_RACE = "beneficiary_race"
    MEDICARE_PAYMENT = "medicare_payment"
    INPATIENT_PAYMENT = "inpatient_payment"
    INPATIENT_VISITS = "inpatient_visits"
    OUTPATIENT = "outpatient"
    AMBULATORY_SURGICAL_CENTER = "ambulatory_surgical_center"
    SKILLED_NURSING_FACILITY = "skilled_nursing_facility"
    INPATIENT_REHABILITATION_FACILITY = "inpatient_rehabilitation_facility"
    LONG_TERM_CARE_HOSPITALS = "long_term_care_hospitals"
    HOME_HEALTH = "home_health"
    HOSPICE = "hospice"
    EVALUATION_MANAGEMENT = "evaluation_management"
    PROCEDURES = "procedures"
    TESTS = "tests"
    IMAGING = "imaging"
    DURABLE_MEDICAL_EQUIPMENT = "durable_medical_equipment"
    DIALYSIS = "dialysis"
    FQHC_RHC = "fqhc_rhc"
    AMBULANCE = "ambulance"
    TREATMENTS = "treatments"
    PART_B = "part_b"
    ADMISSION_RATES = "admission_rates"

MEASURE_COLS = {
    Measure.BENEFICIARIES_COUNT: [
        "BENES_TOTAL_CNT",
        "BENES_WTH_PTAPTB_CNT",
        "BENES_FFS_CNT",
        "BENES_MA_CNT",
    ],
    Measure.BENEFICIARY_GENDER: [
        "BENE_FEML_PCT",
        "BENE_MALE_PCT",
    ],
    Measure.BENEFICIARY_RACE: [
        "BENE_RACE_WHT_PCT",
        "BENE_RACE_BLACK_PCT",
        "BENE_RACE_HSPNC_PCT",
        "BENE_RACE_OTHR_PCT",
    ],
    Measure.MEDICARE_PAYMENT: [
        "TOT_MDCR_PYMT_AMT",
        "TOT_MDCR_STDZD_PYMT_AMT",
        "TOT_MDCR_PYMT_PC",
        "TOT_MDCR_STDZD_PYMT_PC",
    ],
    Measure.INPATIENT_PAYMENT: [
        "IP_MDCR_PYMT_AMT",
        "IP_MDCR_PYMT_PCT",
        "IP_MDCR_PYMT_PC",
        "IP_MDCR_PYMT_PER_USER",
        "IP_MDCR_STDZD_PYMT_AMT",
        "IP_MDCR_STDZD_PYMT_PCT",
        "IP_MDCR_STDZD_PYMT_PC",
        "IP_MDCR_STDZD_PYMT_PER_USER",
        "BENES_IP_CVRD_STAY_CNT",
        "BENES_IP_PCT",
        "IP_CVRD_STAYS_PER_1000_BENES",
        "IP_CVRD_DAYS_PER_1000_BENES",
    ],
    Measure.INPATIENT_VISITS: [
        "ACUTE_HOSP_READMSN_CNT",
        "ACUTE_HOSP_READMSN_PCT",
        "BENES_ER_VISITS_CNT",
        "ER_VISITS_PER_1000_BENES",
        "BENES_ER_VISITS_PCT",
    ],
    Measure.OUTPATIENT: [
        "OP_MDCR_PYMT_AMT",
        "OP_MDCR_PYMT_PCT",
        "OP_MDCR_PYMT_PC",
        "OP_MDCR_PYMT_PER_USER",
        "OP_MDCR_STDZD_PYMT_AMT",
        "OP_MDCR_STDZD_PYMT_PCT",
        "OP_MDCR_STDZD_PYMT_PC",
        "OP_MDCR_STDZD_PYMT_PER_USER",
        "BENES_OP_CNT",
        "BENES_OP_PCT",
    ],
    Measure.AMBULATORY_SURGICAL_CENTER: [
        "ASC_MDCR_PYMT_AMT",
        "ASC_MDCR_PYMT_PCT",
        "ASC_MDCR_PYMT_PC",
        "ASC_MDCR_PYMT_PER_USER",
        "ASC_MDCR_STDZD_PYMT_AMT",
        "ASC_MDCR_STDZD_PYMT_PCT",
        "ASC_MDCR_STDZD_PYMT_PC",
        "ASC_MDCR_STDZD_PYMT_PER_USER",
        "BENES_ASC_CNT",
        "BENES_ASC_PCT",
        "ASC_EVNTS_PER_1000_BENES",
    ],
    Measure.SKILLED_NURSING_FACILITY: [
        "SNF_MDCR_PYMT_AMT",
        "SNF_MDCR_PYMT_PCT",
        "SNF_MDCR_PYMT_PC",
        "SNF_MDCR_PYMT_PER_USER",
        "SNF_MDCR_STDZD_PYMT_AMT",
        "SNF_MDCR_STDZD_PYMT_PCT",
        "SNF_MDCR_STDZD_PYMT_PC",
        "SNF_MDCR_STDZD_PYMT_PER_USER",
        "BENES_SNF_CNT",
        "BENES_SNF_PCT",
        "SNF_CVRD_STAYS_PER_1000_BENES",
        "SNF_CVRD_DAYS_PER_1000_BENES",
    ],
    Measure.INPATIENT_REHABILITATION_FACILITY: [
        "IRF_MDCR_PYMT_AMT",
        "IRF_MDCR_PYMT_PCT",
        "IRF_MDCR_PYMT_PC",
        "IRF_MDCR_PYMT_PER_USER",
        "IRF_MDCR_STDZD_PYMT_AMT",
        "IRF_MDCR_STDZD_PYMT_PCT",
        "IRF_MDCR_STDZD_PYMT_PC",
        "IRF_MDCR_STDZD_PYMT_PER_USER",
        "BENES_IRF_CNT",
        "BENES_IRF_PCT",
        "IRF_CVRD_STAYS_PER_1000_BENES",
        "IRF_CVRD_DAYS_PER_1000_BENES",
    ],
    Measure.LONG_TERM_CARE_HOSPITALS: [
        "LTCH_MDCR_PYMT_AMT",
        "LTCH_MDCR_PYMT_PCT",
        "LTCH_MDCR_PYMT_PC",
        "LTCH_MDCR_PYMT_PER_USER",
        "LTCH_MDCR_STDZD_PYMT_AMT",
        "LTCH_MDCR_STDZD_PYMT_PCT",
        "LTCH_MDCR_STDZD_PYMT_PC",
        "LTCH_MDCR_STDZD_PYMT_PER_USER",
        "BENES_LTCH_CNT",
        "BENES_LTCH_PCT",
        "LTCH_CVRD_STAYS_PER_1000_BENES",
        "LTCH_CVRD_DAYS_PER_1000_BENES",
    ],
    Measure.HOME_HEALTH: [
        "HH_MDCR_PYMT_AMT",
        "HH_MDCR_PYMT_PCT",
        "HH_MDCR_PYMT_PC",
        "HH_MDCR_PYMT_PER_USER",
        "HH_MDCR_STDZD_PYMT_AMT",
        "HH_MDCR_STDZD_PYMT_PCT",
        "HH_MDCR_STDZD_PYMT_PC",
        "HH_MDCR_STDZD_PYMT_PER_USER",
        "BENES_HH_CNT",
        "BENES_HH_PCT",
        "HH_EPISODES_PER_1000_BENES",
        "HH_VISITS_PER_1000_BENES",
    ],
    Measure.HOSPICE: [
        "HOSPC_MDCR_PYMT_AMT",
        "HOSPC_MDCR_PYMT_PCT",
        "HOSPC_MDCR_PYMT_PC",
        "HOSPC_MDCR_PYMT_PER_USER",
        "HOSPC_MDCR_STDZD_PYMT_AMT",
        "HOSPC_MDCR_STDZD_PYMT_PCT",
        "HOSPC_MDCR_STDZD_PYMT_PC",
        "HOSPC_MDCR_STDZD_PYMT_PER_USER",
        "BENES_HOSPC_CNT",
        "BENES_HOSPC_PCT",
        "HOSPC_CVRD_STAYS_PER_1000_BENES",
        "HOSPC_CVRD_DAYS_PER_1000_BENES",
    ],
    Measure.EVALUATION_MANAGEMENT: [
        "EM_MDCR_PYMT_AMT",
        "EM_MDCR_PYMT_PCT",
        "EM_MDCR_PYMT_PC",
        "EM_MDCR_PYMT_PER_USER",
        "EM_MDCR_STDZD_PYMT_AMT",
        "EM_MDCR_STDZD_PYMT_PCT",
        "EM_MDCR_STDZD_PYMT_PC",
        "EM_MDCR_STDZD_PYMT_PER_USER",
        "BENES_EM_CNT",
        "BENES_EM_PCT",
        "EM_EVNTS_PER_1000_BENES",
    ],
    Measure.PROCEDURES: [
        "PRCDRS_MDCR_PYMT_AMT",
        "PRCDRS_MDCR_PYMT_PCT",
        "PRCDRS_MDCR_PYMT_PC",
        "PRCDRS_MDCR_PYMT_PER_USER",
        "PRCDRS_MDCR_STDZD_PYMT_AMT",
        "PRCDRS_MDCR_STDZD_PYMT_PCT",
        "PRCDRS_MDCR_STDZD_PYMT_PC",
        "PRCDRS_MDCR_STDZD_PYMT_PER_USER",
        "BENES_PRCDRS_CNT",
        "BENES_PRCDRS_PCT",
        "PRCDR_EVNTS_PER_1000_BENES",
    ],
    Measure.TESTS: [
        "TESTS_MDCR_PYMT_AMT",
        "TESTS_MDCR_PYMT_PCT",
        "TESTS_MDCR_PYMT_PC",
        "TESTS_MDCR_PYMT_PER_USER",
        "TESTS_MDCR_STDZD_PYMT_AMT",
        "TESTS_MDCR_STDZD_PYMT_PCT",
        "TESTS_MDCR_STDZD_PYMT_PC",
        "TESTS_MDCR_STDZD_PYMT_PER_USER",
        "BENES_TESTS_CNT",
        "BENES_TESTS_PCT",
        "TESTS_EVNTS_PER_1000_BENES",
    ],
    Measure.IMAGING: [
        "IMGNG_MDCR_PYMT_AMT",
        "IMGNG_MDCR_PYMT_PCT",
        "IMGNG_MDCR_PYMT_PC",
        "IMGNG_MDCR_PYMT_PER_USER",
        "IMGNG_MDCR_STDZD_PYMT_AMT",
        "IMGNG_MDCR_STDZD_PYMT_PCT",
        "IMGNG_MDCR_STDZD_PYMT_PC",
        "IMGNG_MDCR_STDZD_PYMT_PER_USER",
        "BENES_IMGNG_CNT",
        "BENES_IMGNG_PCT",
        "IMGNG_EVNTS_PER_1000_BENES",
    ],
    Measure.DURABLE_MEDICAL_EQUIPMENT: [
        "DME_MDCR_PYMT_AMT",
        "DME_MDCR_PYMT_PCT",
        "DME_MDCR_PYMT_PC",
        "DME_MDCR_PYMT_PER_USER",
        "DME_MDCR_STDZD_PYMT_AMT",
        "DME_MDCR_STDZD_PYMT_PCT",
        "DME_MDCR_STDZD_PYMT_PC",
        "DME_MDCR_STDZD_PYMT_PER_USER",
        "BENES_DME_CNT",
        "BENES_DME_PCT",
        "DME_EVNTS_PER_1000_BENES",
    ],
    Measure.DIALYSIS: [
        "OP_DLYS_MDCR_PYMT_AMT",
        "OP_DLYS_MDCR_PYMT_PCT",
        "OP_DLYS_MDCR_PYMT_PC",
        "OP_DLYS_MDCR_PYMT_PER_USER",
        "OP_DLYS_MDCR_STDZD_PYMT_AMT",
        "OP_DLYS_MDCR_STDZD_PYMT_PCT",
        "OP_DLYS_MDCR_STDZD_PYMT_PC",
        "OP_DLYS_MDCR_STDZD_PYMT_PER_USER",
        "BENES_OP_DLYS_CNT",
        "BENES_OP_DLYS_PCT",
        "OP_DLYS_VISITS_PER_1000_BENES",
    ],
    Measure.FQHC_RHC: [
        "FQHC_RHC_MDCR_PYMT_AMT",
        "FQHC_RHC_MDCR_PYMT_PCT",
        "FQHC_RHC_MDCR_PYMT_PC",
        "FQHC_RHC_MDCR_PYMT_PER_USER",
        "FQHC_RHC_MDCR_STDZD_PYMT_AMT",
        "FQHC_RHC_MDCR_STDZD_PYMT_PCT",
        "FQHC_RHC_MDCR_STDZD_PYMT_PC",
        "FQHC_RHC_MDCR_STDZD_PYMT_PU",
        "BENES_FQHC_RHC_CNT",
        "BENES_FQHC_RHC_PCT",
        "FQHC_RHC_VISITS_PER_1000_BENES",
    ],
    Measure.AMBULANCE: [
        "AMBLNC_MDCR_PYMT_AMT",
        "AMBLNC_MDCR_PYMT_PCT",
        "AMBLNC_MDCR_PYMT_PC",
        "AMBLNC_MDCR_PYMT_PER_USER",
        "AMBLNC_MDCR_STDZD_PYMT_AMT",
        "AMBLNC_MDCR_STDZD_PYMT_PCT",
        "AMBLNC_MDCR_STDZD_PYMT_PC",
        "AMBLNC_MDCR_STDZD_PYMT_PER_USER",
        "BENES_AMBLNC_CNT",
        "BENES_AMBLNC_PCT",
        "AMBLNC_EVNTS_PER_1000_BENES",
    ],
    Measure.TREATMENTS: [
        "TRTMNTS_MDCR_PYMT_AMT",
        "TRTMNTS_MDCR_PYMT_PCT",
        "TRTMNTS_MDCR_PYMT_PC",
        "TRTMNTS_MDCR_PYMT_PER_USER",
        "TRTMNTS_MDCR_STDZD_PYMT_AMT",
        "TRTMNTS_MDCR_STDZD_PYMT_PCT",
        "TRTMNTS_MDCR_STDZD_PYMT_PC",
        "TRTMNTS_MDCR_STDZD_PYMT_PER_USER",
        "BENES_TRTMNTS_CNT",
        "BENES_TRTMNTS_PCT",
        "TRTMNTS_EVNTS_PER_1000_BENES",
    ],
    Measure.PART_B: [
        "PTB_OTHR_SRVCS_MDCR_PYMT_AMT",
        "PTB_OTHR_SRVCS_MDCR_STDZD_PYMT",
    ],
    Measure.ADMISSION_RATES: [
        "PQI03_DBTS_AGE_LT_65",
        "PQI03_DBTS_AGE_65_74",
        "PQI03_DBTS_AGE_GE_75",
        "PQI05_COPD_ASTHMA_AGE_40_64",
        "PQI05_COPD_ASTHMA_AGE_65_74",
        "PQI05_COPD_ASTHMA_AGE_GE_75",
        "PQI07_HYPRTNSN_AGE_LT_65",
        "PQI07_HYPRTNSN_AGE_65_74",
        "PQI07_HYPRTNSN_AGE_GE_75",
        "PQI08_CHF_AGE_LT_65",
        "PQI08_CHF_AGE_65_74",
        "PQI08_CHF_AGE_GE_75",
        "PQI11_BCTRL_PNA_AGE_LT_65",
        "PQI11_BCTRL_PNA_AGE_65_74",
        "PQI11_BCTRL_PNA_AGE_GE_75",
        "PQI12_UTI_AGE_LT_65",
        "PQI12_UTI_AGE_65_74",
        "PQI12_UTI_AGE_GE_75",
        "PQI15_ASTHMA_AGE_LT_40",
        "PQI16_LWRXTRMTY_AMPUTN_AGE_LT_65",
        "PQI16_LWRXTRMTY_AMPUTN_AGE_65_74",
        "PQI16_LWRXTRMTY_AMPUTN_AGE_GE_75",
    ],
}
